# Create csi-helper Deployment if CSI is enabled and csi.deploymentStrategy is
# "deployment".
{{- if and .Values.csi.enable (eq .Values.csi.deploymentStrategy "deployment") }}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "storageos.fullname" . }}-csi-helper
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "storageos.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "storageos.name" . }}
        chart: {{ template "storageos.chart" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        kind: deployment
    spec:
      serviceAccount: {{ template "storageos.fullname" . }}-csi-helper-sa
      containers:
      - name: csi-external-provisioner
        image: "{{ .Values.csiExternalProvisioner.repository }}:{{ .Values.csiExternalProvisioner.tag }}"
        imagePullPolicy: {{ .Values.csiExternalProvisioner.pullPolicy }}
        args:
          - "--v=5"
          - "--provisioner=storageos"
          - "--csi-address=$(ADDRESS)"
        env:
          - name: ADDRESS
            value: /csi/csi.sock # plugin-dir is mounted at /csi
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi
      - name: csi-external-attacher
        image: "{{ .Values.csiExternalAttacher.repository }}:{{ .Values.csiExternalAttacher.tag }}"
        imagePullPolicy: {{ .Values.csiExternalAttacher.pullPolicy }}
        args:
          - "--v=5"
          - "--csi-address=$(ADDRESS)"
        env:
          - name: ADDRESS
            value: /csi/csi.sock
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi
      - name: csi-cluster-driver-registrar
        image: "{{ .Values.csiClusterDriverRegistrar.repository }}:{{ .Values.csiClusterDriverRegistrar.tag }}"
        imagePullPolicy: {{ .Values.csiClusterDriverRegistrar.pullPolicy }}
        args:
          - "--v=5"
          - "--csi-address=$(ADDRESS)"
          - "--pod-info-mount-version=v1"
        env:
          - name: ADDRESS
            value: /csi/csi.sock
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/storageos/
            type: DirectoryOrCreate
      # Add toleration for quicker termination of pod and recovery in case of a
      # node failure.
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 30
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 30

{{- end }}
