{{- if .Values.csi.enable }}

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageclass.name }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
provisioner: storageos
parameters:
  pool: {{ .Values.storageclass.pool }}
  # Value with space is an invalid label in CSI volumes.
  # description: Kubernetes volume
  csi.storage.k8s.io/fstype: {{ .Values.storageclass.fsType }}

  # CSI credentials config.
  {{- if .Values.csi.provisionCreds.enable }}
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.csi.provisionCreds.secretName }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  {{- end }}

  {{- if .Values.csi.controllerPublishCreds.enable }}
  csi.storage.k8s.io/controller-publish-secret-name: {{ .Values.csi.controllerPublishCreds.secretName }}
  csi.storage.k8s.io/controller-publish-secret-namespace: {{ .Release.Namespace }}
  {{- end}}

  {{- if .Values.csi.nodeStageCreds.enable }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Values.csi.nodeStageCreds.secretName }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Release.Namespace }}
  {{- end }}

  {{- if .Values.csi.nodePublishCreds.enable }}
  csi.storage.k8s.io/node-publish-secret-name: {{ .Values.csi.nodePublishCreds.secretName }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ .Release.Namespace }}
  {{- end }}

---

# Role for Key Management.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: key-management-role
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]

---

# Role for Driver Registrar.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: driver-registrar-role
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csidrivers"]
    verbs: ["create"]

---

# Service account for StorageOS DaemonSet.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "storageos.fullname" . }}-daemonset-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

---

# Bind DaemonSet Service account to Driver Registrar role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: driver-registrar-binding
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "storageos.fullname" . }}-daemonset-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: driver-registrar-role
  apiGroup: rbac.authorization.k8s.io

---

# Bind DaemonSet Service account to Key Management role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: key-management-binding
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "storageos.fullname" . }}-daemonset-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: key-management-role
  apiGroup: rbac.authorization.k8s.io

---

# Role for CSI External Provisioner.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-role
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["list", "watch", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---

# Role for CSI External Attacher.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["list", "watch", "get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---

{{- if eq .Values.csi.deploymentStrategy "deployment" }}

# Service Account for CSI helper Deployment.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "storageos.fullname" . }}-csi-helper-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}


{{- else }}

# Service Account for StorageOS StatefulSet.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "storageos.fullname" . }}-statefulset-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

{{- end }}

---

# Bind CSI helper service account to External Provisioner role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-binding
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    {{- if eq .Values.csi.deploymentStrategy "deployment" }}
    name: {{ template "storageos.fullname" . }}-csi-helper-sa
    {{- else }}
    name: {{ template "storageos.fullname" . }}-statefulset-sa
    {{- end }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-provisioner-role
  apiGroup: rbac.authorization.k8s.io

---

# Bind CSI helper service account to External Attacher role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-binding
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    {{- if eq .Values.csi.deploymentStrategy "deployment" }}
    name: {{ template "storageos.fullname" . }}-csi-helper-sa
    {{- else }}
    name: {{ template "storageos.fullname" . }}-statefulset-sa
    {{- end }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-attacher-role
  apiGroup: rbac.authorization.k8s.io

---

# Bind CSI helper service account to Key Management role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-key-management-binding
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    {{- if eq .Values.csi.deploymentStrategy "deployment" }}
    name: {{ template "storageos.fullname" . }}-csi-helper-sa
    {{- else }}
    name: {{ template "storageos.fullname" . }}-statefulset-sa
    {{- end }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: key-management-role
  apiGroup: rbac.authorization.k8s.io

---

# Binding CSI helper service account to Driver Registrar role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-driver-registrar-binding
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    {{- if eq .Values.csi.deploymentStrategy "deployment" }}
    name: {{ template "storageos.fullname" . }}-csi-helper-sa
    {{- else }}
    name: {{ template "storageos.fullname" . }}-statefulset-sa
    {{- end }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: driver-registrar-role
  apiGroup: rbac.authorization.k8s.io

{{- end }}
