sudo: required

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - K8S_VERSION="v1.10.0"
    - MINIKUBE_VERSION="v0.28.2"
    - CHART_TESTING_IMAGE="gcr.io/kubernetes-charts-ci/chart-testing"
    - CHART_TESTING_TAG="v1.1.0"
    - CHARTS_REPO="https://github.com/storageos/charts"

before_install:
    - docker run -d -p 2399:2399 quay.io/coreos/etcd:v3.3.10 /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2399 -listen-client-urls http://0.0.0.0:2399

script:
    - ./test/e2e-minikube.sh
