# Default values for storageoscluster-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: storageos/cluster-operator
  tag: v0.0.9
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: storageoscluster-operator-sa
